### ISSUE TITLE
Zabbix server is not listening on port 10051

### ISSUE THREAD

**Issue by aanc** [zabbix/zabbix-community-docker#6]
Hello,

When launching the container as described in the README.md, I cannot push data to Zabbix as it seems its not listening on port 10051 (inside the container). Therefore I cannot push data from agents to this server.

Tested with 
. Docker 1.7.1-1.el7.centos.x86_64 on  CentOS Linux release 7.1.1503 (Core)
. Docker version 1.6.2, build ba1f6c3/1.6.2`, on CentOS Linux release 7.1.1503 (Core)
. Docker version 1.7.0, build 0baf609, on Ubuntu 15.04

```
$ docker run -d --name zabbix -p 8080:80 -p 10051:10051 --env="DB_ADDRESS=192.168.33.10" --env="DB_USER=zabbix" --env="DB_PASS=zabbix" zabbix/zabbix-server-2.4:2.4.4
2c081abf133d1521109256a8e408d0568bb130215f697f6768dfe2acb7bc30bc

$ docker ps
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS                PORTS                                                                NAMES
2c081abf133d        zabbix/zabbix-server-2.4:2.4.4   "/config/bootstrap.s   4 seconds ago       Up 3 seconds        443/tcp, 10052/tcp, 0.0.0.0:10051->10051/tcp, 0.0.0.0:8080->80/tcp   zabbix       
```

The start logs seems OK

```
$ docker logs zabbix
Nginx status page: allowed address set to 127.0.0.1.
PHP-FPM status page: allowed address set to 127.0.0.1.
[LOG 11:33:10] Preparing server configuration
[LOG 11:33:10] Config updated.
[LOG 11:33:10] Enabling Logging and pid management.
[LOG 11:33:10] Done
[LOG 11:33:10] Checking if Database exists or fresh install
[LOG 11:33:10] Zabbix DB Exists. Starting server.
2015-07-23 11:33:10,771 CRIT Supervisor running as root (no user in config file)
2015-07-23 11:33:10,771 WARN Included extra file "/etc/supervisor.d/zabbix.conf" during parsing
2015-07-23 11:33:10,771 WARN Included extra file "/etc/supervisor.d/php-fpm.conf" during parsing
2015-07-23 11:33:10,771 WARN Included extra file "/etc/supervisor.d/nginx.conf" during parsing
2015-07-23 11:33:10,780 INFO RPC interface 'supervisor' initialized
2015-07-23 11:33:10,781 INFO supervisord started with pid 80
2015-07-23 11:33:11,783 INFO spawned: 'nginx' with pid 88
2015-07-23 11:33:11,785 INFO spawned: 'nginx-reload' with pid 89
2015-07-23 11:33:11,786 INFO spawned: 'php-fpm' with pid 90
2015-07-23 11:33:11,788 INFO spawned: 'zabbix-server' with pid 91
2015-07-23 11:33:11,800 DEBG 'nginx' stderr output:
2015/07/23 11:33:11 [notice] 88#0: using the "epoll" event method
2015/07/23 11:33:11 [notice] 88#0: nginx/1.8.0
2015/07/23 11:33:11 [notice] 88#0: built by gcc 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) 
2015/07/23 11:33:11 [notice] 88#0: OS: Linux 3.19.0-22-generic
2015/07/23 11:33:11 [notice] 88#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2015/07/23 11:33:11 [notice] 88#0: start worker processes

2015-07-23 11:33:11,801 DEBG 'nginx' stderr output:
2015/07/23 11:33:11 [notice] 88#0: start worker process 94
2015/07/23 11:33:11 [notice] 88#0: start worker process 95

2015-07-23 11:33:11,801 DEBG 'nginx' stderr output:
2015/07/23 11:33:11 [notice] 88#0: start worker process 96

2015-07-23 11:33:11,801 DEBG 'nginx' stderr output:
2015/07/23 11:33:11 [notice] 88#0: start worker process 97

2015-07-23 11:33:11,865 DEBG fd 13 closed, stopped monitoring <POutputDispatcher at 140625428393136 for <Subprocess at 140625430825584 with name php-fpm in state STARTING> (stdout)>
2015-07-23 11:33:11,865 DEBG 'php-fpm' stderr output:
[23-Jul-2015 11:33:11] WARNING: Nothing matches the include pattern '/data/conf/php-fpm-www-*.conf' from /etc/php-fpm.d/www.conf at line 18.

2015-07-23 11:33:11,866 DEBG fd 17 closed, stopped monitoring <POutputDispatcher at 140625428392848 for <Subprocess at 140625430825584 with name php-fpm in state STARTING> (stderr)>
2015-07-23 11:33:12,867 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-07-23 11:33:12,868 INFO success: nginx-reload entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-07-23 11:33:12,868 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-07-23 11:33:12,868 INFO success: zabbix-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

When diving into the container, there is nothing listening on port 10051

```
$ docker exec -ti 2c081abf133d bash
[root@2c081abf133d /]# netstat -lpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      88/nginx: master pr 
tcp        0      0 0.0.0.0:9111            0.0.0.0:*               LISTEN      80/python           
tcp        0      0 0.0.0.0:10050           0.0.0.0:*               LISTEN      -                   
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     27530893 90/php-fpm: master   /var/run/php-fpm-www.sock
```

However, all required processes seems to be here, especially `zabbix_server`

```
[root@2c081abf133d /]# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 11:33 ?        00:00:00 /bin/bash /config/bootstrap.sh
zabbix      79     1  0 11:33 ?        00:00:00 zabbix_agentd -c /usr/local/etc/zabbix_agentd.conf
root        80     1  0 11:33 ?        00:00:00 /usr/bin/python /usr/bin/supervisord -n -c /etc/supervisord.conf
zabbix      81    79  0 11:33 ?        00:00:00 zabbix_agentd: collector [idle 1 sec]
zabbix      82    79  0 11:33 ?        00:00:00 zabbix_agentd: listener #1 [waiting for connection]
zabbix      83    79  0 11:33 ?        00:00:00 zabbix_agentd: listener #2 [waiting for connection]
zabbix      84    79  0 11:33 ?        00:00:00 zabbix_agentd: listener #3 [waiting for connection]
zabbix      85    79  0 11:33 ?        00:00:00 zabbix_agentd: active checks #1 [idle 1 sec]
root        88    80  0 11:33 ?        00:00:00 nginx: master process /usr/sbin/nginx
root        89    80  0 11:33 ?        00:00:00 bash -c while inotifywait -q -r -e create,delete,modify,move,attrib --exclude "/\." /etc/nginx/ /data/conf/nginx/; do nginx -t && nginx -s reload; done
root        90    80  0 11:33 ?        00:00:00 php-fpm: master process (/etc/php-fpm.conf)
root        91    80  0 11:33 ?        00:00:00 /bin/sh /config/ds.sh /var/run/zabbix_server.pid zabbix_server -c /usr/local/etc/zabbix_server.conf
root        92    89  0 11:33 ?        00:00:00 inotifywait -q -r -e create,delete,modify,move,attrib --exclude /\. /etc/nginx/ /data/conf/nginx/
www         94    88  0 11:33 ?        00:00:00 nginx: worker process
www         95    88  0 11:33 ?        00:00:00 nginx: worker process
www         96    88  0 11:33 ?        00:00:00 nginx: worker process
www         97    88  0 11:33 ?        00:00:00 nginx: worker process
zabbix      99     1  0 11:33 ?        00:00:00 zabbix_server -c /usr/local/etc/zabbix_server.conf
root       542     0  0 11:35 ?        00:00:00 bash
root      1194    91  0 11:37 ?        00:00:00 sleep 0.5
root      1195   542  0 11:37 ?        00:00:00 ps -ef
```

Server conf is the default one

```
[root@2c081abf133d /]# sed -e '/^#/d' -e '/^$/d' /usr/local/etc/zabbix_server.conf
LogFile=/var/log/zabbix/zabbix_server.log
DebugLevel=0
PidFile=/var/run/zabbix_server.pid
DBHost=zabbix.db
DBName=zabbix
DBUser=zabbix
DBPassword=zabbix
StartPollers=1
StartIPMIPollers=1
StartTrappers=1
JavaGateway=127.0.0.1
StartJavaPollers=1
StartVMwareCollectors=1
VMwareFrequency=10
VMwareCacheSize=256K
SNMPTrapperFile=/var/log/snmptt/snmptt.log
SenderFrequency=10
CacheUpdateFrequency=10
StartDBSyncers=1
HistoryCacheSize=8M
TrendCacheSize=4M
HistoryTextCacheSize=16M
ValueCacheSize=8M
Timeout=30
UnreachablePeriod=10
UnavailableDelay=10
UnreachableDelay=10
```

Zabbix server logs says nothing about not being able to listen on port 10051

```
[root@2c081abf133d /]# cat /var/log/zabbix/zabbix_server.log 
    99:20150723:113311.808 Starting Zabbix Server. Zabbix 2.4.4 (revision {ZABBIX_REVISION}).
    99:20150723:113311.808 ****** Enabled features ******
    99:20150723:113311.808 SNMP monitoring:           YES
    99:20150723:113311.808 IPMI monitoring:           YES
    99:20150723:113311.808 WEB monitoring:            YES
    99:20150723:113311.808 VMware monitoring:         YES
    99:20150723:113311.808 Jabber notifications:       NO
    99:20150723:113311.809 Ez Texting notifications:  YES
    99:20150723:113311.809 ODBC:                       NO
    99:20150723:113311.809 SSH2 support:               NO
    99:20150723:113311.809 IPv6 support:               NO
    99:20150723:113311.809 ******************************
    99:20150723:113311.809 using configuration file: /usr/local/etc/zabbix_server.conf
```

I hope I'm using this image correctly. Let me know if you need more info.
Thanks in advance for your help!

**Comment by jangaraj** [comment]
Hi Adrien,

Are you able to test it with latest tag please? (Keep in mind that your Zabbix DB can be upgraded).

IMHO it's a problem - https://github.com/zabbix/zabbix-community-docker/pull/5/files
Pull request has been applied only to master branch tag latest/2.4.5. Older tags (your 2.4.4 as well) have still this problem. We need to retag/rebuild all layers/images.

**Comment by aanc** [comment]
Hi Jan, thanks for your help !

I tested with tags 2.4.5 and latest, (with a fresh docker pull in order to be sure to have the latest latest), and it did not resolved my issue.
I also tested with a `million12/mariadb` container as database, hosted on the same host; it did not help.

Is it normal that when I open my browser, after launching the zabbix-server container, I get the Zabbix setup page ? It ask to enter DB details, I do it, test it (it says OK), and then login and arrive on Zabbix's Dashboard, where I have a big red message saying "Zabbix server is not running, information may not be current". I expected not to have to give DB details again, as I gave them in the docker run command line.

Let me know if you want me to run some more tests !

**Comment by pozgo** [comment]
HI,

What did you put in at this stage? 

![screen shot 2015-07-23 at 14 11 44](https://cloud.githubusercontent.com/assets/1773188/8851071/ed24b518-3144-11e5-962e-9fc525dde1ad.jpg)

It should be left with localhost. Just edit the name oz zabbix server that you want to have. 

Hope that helps

**Comment by aanc** [comment]
I left it as described on the screenshot.

When I go into the container as described in my first post, I still have nothing listening on port 10051 (check with netstat and ss), but zabbix_server process is running (check with ps).

When I `docker inspect` my container and get its internal IP, and try telneting it, it says:

```
$ telnet 172.17.0.16 10051
Trying 172.17.0.16...
telnet: Unable to connect to remote host: Connection refused
```

confirming that nothing is listening on 10051.

The container's docker inspect :

```
[
{
    "Id": "fae32d42e4191bf5f95d03235d3492ad425c8f86fd86096c262a6a339ff3d001",
    "Created": "2015-07-23T12:57:15.630961806Z",
    "Path": "/config/bootstrap.sh",
    "Args": [],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 29634,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-07-23T12:57:15.777229954Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "6c24ceea5aef42003c9e4d3f5bab577314c51da8062048f7e04a80d9516afebc",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "e095296d88baa41cadd874187d76f19d6b6ed26eda0ccf32fcd880a9a741ce26",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.16",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:10",
        "NetworkID": "3156c0b260472f9c1e38f045e0187bf8984ca3410a7d299b7b4de0a4e9aa8df6",
        "PortMapping": null,
        "Ports": {
            "10051/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "10051"
                }
            ],
            "10052/tcp": null,
            "443/tcp": null,
            "80/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8080"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/fae32d42e419",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/fae32d42e4191bf5f95d03235d3492ad425c8f86fd86096c262a6a339ff3d001/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/fae32d42e4191bf5f95d03235d3492ad425c8f86fd86096c262a6a339ff3d001/hostname",
    "HostsPath": "/var/lib/docker/containers/fae32d42e4191bf5f95d03235d3492ad425c8f86fd86096c262a6a339ff3d001/hosts",
    "LogPath": "/var/lib/docker/containers/fae32d42e4191bf5f95d03235d3492ad425c8f86fd86096c262a6a339ff3d001/fae32d42e4191bf5f95d03235d3492ad425c8f86fd86096c262a6a339ff3d001-json.log",
    "Name": "/zabbix",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "Volumes": {
        "/data": "/var/lib/docker/volumes/4afb7c3bddf21e12080c3191a3d3cde277592f616abc76ea14d00822572f117c/_data"
    },
    "VolumesRW": {
        "/data": true
    },
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "Privileged": false,
        "PortBindings": {
            "10051/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "10051"
                }
            ],
            "80/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8080"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": ""
    },
    "Config": {
        "Hostname": "fae32d42e419",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "PortSpecs": null,
        "ExposedPorts": {
            "10051/tcp": {},
            "10052/tcp": {},
            "443/tcp": {},
            "80/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "DB_ADDRESS=192.168.33.1",
            "DB_USER=username",
            "DB_PASS=my_password",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "STATUS_PAGE_ALLOWED_IP=127.0.0.1",
            "ZABBIX_VERSION=2.4.5",
            "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk/bin/java",
            "JAVA=/usr/lib/jvm/java-1.8.0-openjdk/bin/java"
        ],
        "Cmd": null,
        "Image": "zabbix/zabbix-server-2.4:latest",
        "Volumes": {
            "/data": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": [
            "/config/bootstrap.sh"
        ],
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]
```

**Comment by pozgo** [comment]
I think I have spotted why it's not listening on port 10051. Apparently zabbix_agent that is compiled inside this image is not being patched to work in foreground in docker. I never spotted that as I'm using my own docker image with zabbix agent separately. [million12/zabbix-agent](https://github.com/million12/docker-zabbix-agent).

I'll try to transfer those changes when I find some spare time into official image here. Unless someone wants to do before me :)

**Comment by pozgo** [comment]
Fixed latest and 2.4.5... We would need to go through all previous builds and check if this patch actually works on any release before 2.4.5.

**Comment by jangaraj** [comment]
I think that zabbix-agent should be different Docker community image. (Then I'll create customized agent image with docker monitoring module and it'll be competitor for cAdvisor :-D - still in my TODO list).

**Comment by pozgo** [comment]
@jangaraj I totally agree... 

I have my own image but just lack of time preparing a whole new repo for zabbix community. :) I hope next month will find some to make it happen, unless someone else want to do it of course. 

for time being i propose to use [million12/zabbix-agent](https://registry.hub.docker.com/u/million12/zabbix-agent/)

**Comment by inevu** [comment]
Hi @pozgo 

I'm still getting the same behavior with  `zabbix/zabbix-server-2.4:2.4.5`. 

Zabbix is not listening on port 10051 after the container gets started.

Command:

```
docker run --rm --name zabbix -p 80:80 -p 10051:10051 --env="DB_ADDRESS=172.17.0.1" --env="DB_USER=zabbix" --env="DB_PASS=zabbix" zabbix/zabbix-server-2.4:2.4.5
```

Output of `netstat -na` inside the container:

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:10050           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:9111            0.0.0.0:*               LISTEN     
tcp        0      0 172.17.0.7:38365        172.17.0.1:3306         TIME_WAIT  
```

zabbix_agent log:

```
    86:20150804:235127.383 Starting Zabbix Agent [Zabbix server]. Zabbix 2.4.5 (revision {ZABBIX_REVISION}).
    86:20150804:235127.383 using configuration file: /usr/local/etc/zabbix_agentd.conf
    86:20150804:235127.384 agent #0 started [main process]
   105:20150804:235127.384 agent #1 started [collector]
   106:20150804:235127.384 agent #2 started [listener #1]
   107:20150804:235127.385 agent #3 started [listener #2]
   108:20150804:235127.385 agent #4 started [listener #3]
   109:20150804:235127.385 agent #5 started [active checks #1]
   109:20150804:235127.385 active check configuration update from [127.0.0.1:10051] started to fail (cannot connect to [[127.0.0.1]:10051]: [111] Connection refused)
```

Output of zabbix_server.log:

```
   111:20150804:235127.388 Starting Zabbix Server. Zabbix 2.4.5 (revision {ZABBIX_REVISION}).
   111:20150804:235127.388 ****** Enabled features ******
   111:20150804:235127.388 SNMP monitoring:           YES
   111:20150804:235127.388 IPMI monitoring:           YES
   111:20150804:235127.388 WEB monitoring:            YES
   111:20150804:235127.388 VMware monitoring:         YES
   111:20150804:235127.388 Jabber notifications:       NO
   111:20150804:235127.388 Ez Texting notifications:  YES
   111:20150804:235127.388 ODBC:                       NO
   111:20150804:235127.388 SSH2 support:               NO
   111:20150804:235127.388 IPv6 support:               NO
   111:20150804:235127.388 ******************************
   111:20150804:235127.388 using configuration file: /usr/local/etc/zabbix_server.conf
```

Output of `docker inspect`:

```
[{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "AttachStderr": true,
        "AttachStdin": false,
        "AttachStdout": true,
        "Cmd": null,
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": [
            "/config/bootstrap.sh"
        ],
        "Env": [
            "DB_ADDRESS=172.17.0.1",
            "DB_USER=zabbix",
            "DB_PASS=zabbix",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "STATUS_PAGE_ALLOWED_IP=127.0.0.1",
            "ZABBIX_VERSION=2.4.5",
            "JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk/bin/java",
            "JAVA=/usr/lib/jvm/java-1.8.0-openjdk/bin/java"
        ],
        "ExposedPorts": {
            "10051/tcp": {},
            "10052/tcp": {},
            "443/tcp": {},
            "80/tcp": {}
        },
        "Hostname": "318e61e34068",
        "Image": "zabbix/zabbix-server-2.4:2.4.5",
        "Labels": {},
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": null,
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/data": {}
        },
        "WorkingDir": ""
    },
    "Created": "2015-08-04T23:51:15.120734484Z",
    "Driver": "devicemapper",
    "ExecDriver": "native-0.2",
    "ExecIDs": [
        "c7c928d13368e06f682c5125b2ec06b1e3957569f02d056acd2728e6d062e58e"
    ],
    "HostConfig": {
        "Binds": null,
        "CapAdd": null,
        "CapDrop": null,
        "CgroupParent": "",
        "ContainerIDFile": "",
        "CpuShares": 0,
        "CpusetCpus": "",
        "Devices": [],
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "IpcMode": "",
        "Links": null,
        "LogConfig": {
            "Config": null,
            "Type": "json-file"
        },
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkMode": "bridge",
        "PidMode": "",
        "PortBindings": {
            "10051/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "10051"
                }
            ],
            "80/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "80"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "no"
        },
        "SecurityOpt": null,
        "Ulimits": null,
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/318e61e3406816224f633757babad6cb5f0e537b6ea39bb45c2d86c9d1acbe6f/hostname",
    "HostsPath": "/var/lib/docker/containers/318e61e3406816224f633757babad6cb5f0e537b6ea39bb45c2d86c9d1acbe6f/hosts",
    "Id": "318e61e3406816224f633757babad6cb5f0e537b6ea39bb45c2d86c9d1acbe6f",
    "Image": "3fcc2bbb5b8a55a22e770b5967d60355f62f53c732e6c7ef2ff874a315cc3a01",
    "LogPath": "/var/lib/docker/containers/318e61e3406816224f633757babad6cb5f0e537b6ea39bb45c2d86c9d1acbe6f/318e61e3406816224f633757babad6cb5f0e537b6ea39bb45c2d86c9d1acbe6f-json.log",
    "MountLabel": "system_u:object_r:svirt_sandbox_file_t:s0:c534,c708",
    "Name": "/zabbix",
    "NetworkSettings": {
        "Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.7",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "ac91::34:cadd:ef13:8",
        "LinkLocalIPv6PrefixLen": 64,
        "MacAddress": "30:53:fd:23:01:70",
        "PortMapping": null,
        "Ports": {
            "10051/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "10051"
                }
            ],
            "10052/tcp": null,
            "443/tcp": null,
            "80/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "80"
                }
            ]
        }
    },
    "Path": "/config/bootstrap.sh",
    "ProcessLabel": "system_u:system_r:svirt_lxc_net_t:s0:c534,c708",
    "ResolvConfPath": "/var/lib/docker/containers/318e61e3406816224f633757babad6cb5f0e537b6ea39bb45c2d86c9d1acbe6f/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 3060,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2015-08-04T23:51:19.996321676Z"
    },
    "Volumes": {
        "/data": "/var/lib/docker/vfs/dir/93cac8d3e1c5757c193637a5983b0d289560f6b468c97fdc22c075283a8f9e3c"
    },
    "VolumesRW": {
        "/data": true
    },
    "VolumesRelabel": {
        "/data": ""
    }
}
]
```

Thanks!

**Comment by pozgo** [comment]
Wired. I have just run it and seems to listen on 10051. 

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:10050           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:10051           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:9111            0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.9:52262        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52259        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52252        172.17.0.8:3306         TIME_WAIT
tcp        0      0 172.17.0.9:52263        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52255        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52265        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52246        172.17.0.8:3306         TIME_WAIT
tcp        0      0 172.17.0.9:52250        172.17.0.8:3306         TIME_WAIT
tcp        0      0 172.17.0.9:52258        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52249        172.17.0.8:3306         TIME_WAIT
tcp        0      0 172.17.0.9:52268        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52264        172.17.0.8:3306         TIME_WAIT
tcp        0      0 172.17.0.9:52267        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52256        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52257        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52261        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52266        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52260        172.17.0.8:3306         ESTABLISHED
tcp        0      0 172.17.0.9:52253        172.17.0.8:3306         TIME_WAIT
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     316957   /var/run/php-fpm-www.sock
unix  3      [ ]         STREAM     CONNECTED     316774
unix  3      [ ]         STREAM     CONNECTED     316956
unix  3      [ ]         STREAM     CONNECTED     316775
unix  3      [ ]         STREAM     CONNECTED     316777
unix  3      [ ]         STREAM     CONNECTED     316955
unix  3      [ ]         STREAM     CONNECTED     316776
```

If possible please provide step by step details how did you run those images.

**Comment by inevu** [comment]
1) I am using Docker v1.6.2 on CentOS7.
2) I deleted all the images
3) Run DB container: `docker run -d --name zabbix-db -p 3306:3306 --env="MARIADB_USER=zabbix" --env="MARIADB_PASS=zabbix" million12/mariadb`

```
# docker run -d --name zabbix-db -p 3306:3306 --env="MARIADB_USER=zabbix" --env="MARIADB_PASS=zabbix" million12/mariadb

Unable to find image 'million12/mariadb:latest' locally
latest: Pulling from docker.io/million12/mariadb
f1b10cd84249: Pull complete 
c852f6d61e65: Pull complete 
7322fbe74aa5: Pull complete 
b80ad309220f: Pull complete 
835bebdaaf03: Pull complete 
64e03188732c: Pull complete 
ada6ef4330ad: Pull complete 
3b334be0e9d8: Pull complete 
1b29a42fee64: Pull complete 
ca416a0285f8: Pull complete 
f7f9ce9e7fa5: Already exists 
Digest: sha256:1cbbc205529f3d5a344a0c8008d73ae5c07564ada6af594af8baa588b6918b35
Status: Downloaded newer image for docker.io/million12/mariadb:latest
f3d9b43c2e024dfc00a8fd282617d52c73500339ab8e158e121270a3d8a3e9d0
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
```

4) Look for DB's container IP: `docker inspect --format '{{ .NetworkSettings.IPAddress }}' f3d9`
5) Run zabbix-server container: `docker run -d --name zabbix -p 80:80 -p 10051:10051 --env="DB_ADDRESS=172.17.0.1" --env="DB_USER=zabbix" --env="DB_PASS=zabbix" zabbix/zabbix-server-2.4:2.4.5`

```
#docker run -d --name zabbix -p 80:80 -p 10051:10051 --env="DB_ADDRESS=172.17.0.1" --env="DB_USER=zabbix" --env="DB_PASS=zabbix" zabbix/zabbix-server-2.4:2.4.5

Unable to find image 'zabbix/zabbix-server-2.4:2.4.5' locally
2.4.5: Pulling from docker.io/zabbix/zabbix-server-2.4
87ad98151727: Pull complete 
eed287644906: Pull complete 
137b52230503: Pull complete 
0e4733ad0e9c: Pull complete 
42165a125b27: Pull complete 
e8f0186319e2: Pull complete 
18eb939f3b1d: Pull complete 
9a5c8401f938: Pull complete 
d99c726c21d4: Pull complete 
99ce6cbf18d6: Pull complete 
69c255cee663: Pull complete 
471eeb6c5714: Pull complete 
607cfebddd4c: Pull complete 
8d9d5449151c: Pull complete 
a62bd502edfe: Pull complete 
b986f408ca7b: Pull complete 
452af8dcd8af: Pull complete 
9d2fc99e9221: Pull complete 
f6ce470cf732: Pull complete 
64301946b268: Pull complete 
c017902324e4: Pull complete 
3fcc2bbb5b8a: Already exists 
f1b10cd84249: Already exists 
c852f6d61e65: Already exists 
7322fbe74aa5: Already exists 
Digest: sha256:d8bda0664de1a4a51e7613d8255023f46f8f3bfb631cababae1783a1bba19489
Status: Downloaded newer image for docker.io/zabbix/zabbix-server-2.4:2.4.5
befeac0d50da7bd9e1cb9278d34632fbaa7b8ebf2d25ba70a26e21b5a68c4612
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
```

6) Check output of `docker ps`

```
# docker ps
CONTAINER ID        IMAGE                             COMMAND                CREATED             STATUS              PORTS                                                              NAMES
befeac0d50da        zabbix/zabbix-server-2.4:2.4.5    "/config/bootstrap.s   2 minutes ago       Up 2 minutes        0.0.0.0:80->80/tcp, 443/tcp, 0.0.0.0:10051->10051/tcp, 10052/tcp   zabbix              
f3d9b43c2e02        million12/mariadb:latest          "/run.sh"              5 minutes ago      Up 5 minutes       0.0.0.0:3306->3306/tcp                                             zabbix-db           
```

7) Go into zabbix-server container: `docker exec -it bef bash`
8) Check `netstat -na`:

```
[root@befeac0d50da /]# netstat -na
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:9111            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:10050           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     647642   /var/run/php-fpm-www.sock
unix  3      [ ]         STREAM     CONNECTED     635854   
unix  3      [ ]         STREAM     CONNECTED     635852   
unix  3      [ ]         STREAM     CONNECTED     635857   
unix  3      [ ]         STREAM     CONNECTED     635871   
unix  3      [ ]         STREAM     CONNECTED     635875   
unix  3      [ ]         STREAM     CONNECTED     647641   
unix  3      [ ]         STREAM     CONNECTED     635864   
unix  3      [ ]         STREAM     CONNECTED     647640   
unix  3      [ ]         STREAM     CONNECTED     635876   
unix  3      [ ]         STREAM     CONNECTED     635849   
unix  3      [ ]         STREAM     CONNECTED     635870   
unix  3      [ ]         STREAM     CONNECTED     635859   
unix  3      [ ]         STREAM     CONNECTED     635872   
unix  3      [ ]         STREAM     CONNECTED     635851   
unix  3      [ ]         STREAM     CONNECTED     635878   
unix  3      [ ]         STREAM     CONNECTED     635850   
unix  3      [ ]         STREAM     CONNECTED     635867   
unix  3      [ ]         STREAM     CONNECTED     635855   
unix  3      [ ]         STREAM     CONNECTED     635866   
unix  3      [ ]         STREAM     CONNECTED     635880   
unix  3      [ ]         STREAM     CONNECTED     635853   
unix  3      [ ]         STREAM     CONNECTED     635877   
unix  3      [ ]         STREAM     CONNECTED     635861   
unix  3      [ ]         STREAM     CONNECTED     635860   
unix  3      [ ]         STREAM     CONNECTED     635868   
unix  3      [ ]         STREAM     CONNECTED     635874   
unix  3      [ ]         STREAM     CONNECTED     635862   
unix  3      [ ]         STREAM     CONNECTED     635856   
unix  3      [ ]         STREAM     CONNECTED     635863   
unix  3      [ ]         STREAM     CONNECTED     635858   
unix  3      [ ]         STREAM     CONNECTED     635873   
unix  3      [ ]         STREAM     CONNECTED     635865   
unix  3      [ ]         STREAM     CONNECTED     635879   
unix  3      [ ]         STREAM     CONNECTED     635869   
```

I also tried it on docker v1.6.0 using boot2docker and had the same behavior.

Thanks!

**Comment by pozgo** [comment]
This is all I did:

```
przemek@dev-01 ~ $ docker run \
>   -d \
>   --name zabbix-db \
>   --env="MARIADB_USER=zabbix" \
>   --env="MARIADB_PASS=zabbix" \
>   million12/mariadb
d72d234fb9d63e1f946c17e3e029f6c41f5c8385d9759cc8e2fb900110465054
przemek@dev-01 ~ $ docker logs -f zabbix-db
=> An empty/uninitialized MariaDB volume is detected in /var/lib/mysql
=> Installing MariaDB...
=> Installing MariaDB... Done!
----------------- Previous error log -----------------
150806  6:55:45 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.24-72.2 started; log sequence number 0
150806  6:55:48 [Note] InnoDB: FTS optimize thread exiting.
150806  6:55:48 [Note] InnoDB: Starting shutdown...
150806  6:55:49 [Note] InnoDB: Shutdown completed; log sequence number 1616697
150806  6:55:50 [Note] InnoDB: Using mutexes to ref count buffer pool pages
150806  6:55:50 [Note] InnoDB: The InnoDB memory heap is disabled
150806  6:55:50 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
150806  6:55:50 [Note] InnoDB: Memory barrier is not used
150806  6:55:50 [Note] InnoDB: Compressed tables use zlib 1.2.7
150806  6:55:50 [Note] InnoDB: Using Linux native AIO
150806  6:55:50 [Note] InnoDB: Using CPU crc32 instructions
150806  6:55:50 [Note] InnoDB: Initializing buffer pool, size = 768.0M
150806  6:55:50 [Note] InnoDB: Completed initialization of buffer pool
150806  6:55:50 [Note] InnoDB: Highest supported file format is Barracuda.
150806  6:55:50 [Note] InnoDB: 128 rollback segment(s) are active.
150806  6:55:50 [Note] InnoDB: Waiting for purge to start
150806  6:55:50 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.24-72.2 started; log sequence number 1616697
150806  6:55:50 [Note] InnoDB: FTS optimize thread exiting.
150806  6:55:50 [Note] InnoDB: Starting shutdown...
150806  6:55:52 [Note] InnoDB: Shutdown completed; log sequence number 1616707
----------------- Previous error log ends -----------------

Waiting for DB service...
Still waiting for DB service...
150806 06:55:52 mysqld_safe Logging to '/var/lib/mysql/error.log'.
150806 06:55:52 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
150806 06:55:52 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
150806  6:55:52 [Warning] options --log-slow-admin-statements, --log-queries-not-using-indexes and --log-slow-slave-statements have no effect if --log_slow_queries is not set
150806  6:55:52 [Note] /usr/sbin/mysqld (mysqld 10.0.20-MariaDB) starting as process 240 ...
150806  6:55:52 [Note] InnoDB: Using mutexes to ref count buffer pool pages
150806  6:55:52 [Note] InnoDB: The InnoDB memory heap is disabled
150806  6:55:52 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
150806  6:55:52 [Note] InnoDB: Memory barrier is not used
150806  6:55:52 [Note] InnoDB: Compressed tables use zlib 1.2.7
150806  6:55:52 [Note] InnoDB: Using Linux native AIO
150806  6:55:52 [Note] InnoDB: Using CPU crc32 instructions
150806  6:55:52 [Note] InnoDB: Initializing buffer pool, size = 768.0M
150806  6:55:52 [Note] InnoDB: Completed initialization of buffer pool
150806  6:55:52 [Note] InnoDB: Highest supported file format is Barracuda.
150806  6:55:52 [Note] InnoDB: 128 rollback segment(s) are active.
150806  6:55:52 [Note] InnoDB: Waiting for purge to start
150806  6:55:52 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.24-72.2 started; log sequence number 1616707
150806  6:55:52 [Note] Plugin 'FEEDBACK' is disabled.
150806  6:55:52 [Note] Server socket created on IP: '0.0.0.0'.
150806  6:55:52 [Warning] 'user' entry 'root@d72d234fb9d6' ignored in --skip-name-resolve mode.
150806  6:55:52 [Warning] 'user' entry '@d72d234fb9d6' ignored in --skip-name-resolve mode.
150806  6:55:52 [Warning] 'proxies_priv' entry '@% root@d72d234fb9d6' ignored in --skip-name-resolve mode.
150806  6:55:52 [Note] Event Scheduler: Loaded 0 events
150806  6:55:52 [Note] Reading of all Master_info entries succeded
150806  6:55:52 [Note] Added new Master_info '' to hash table
150806  6:55:52 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.0.20-MariaDB'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MariaDB Server
150806  6:55:52 [Note] /usr/sbin/mysqld: ready for connections.
Securing and tidying DB...
Securing and tidying DB... Done!
Showing DB status...

--------------
mysql  Ver 15.1 Distrib 10.0.20-MariaDB, for Linux (x86_64) using readline 5.1

Connection id:      6
Current database:
Current user:       root@127.0.0.1
SSL:            Not in use
Current pager:      stdout
Using outfile:      ''
Using delimiter:    ;
Server:         MariaDB
Server version:     10.0.20-MariaDB MariaDB Server
Protocol version:   10
Connection:     localhost via TCP/IP
Server characterset:    utf8
Db     characterset:    utf8
Client characterset:    utf8
Conn.  characterset:    utf8
TCP port:       3306
Uptime:         1 sec

Threads: 1  Questions: 16  Slow queries: 1  Opens: 1  Flush tables: 1  Open tables: 64  Queries per second avg: 16.000
--------------

Creating DB admin user...

=> Creating MariaDB user 'zabbix' with 'zabbix' password.
========================================================================
    You can now connect to this MariaDB Server using:
    mysql -uzabbix -pzabbix -h<host>

    For security reasons, you might want to change the above password.
    The 'root' user has no password but only allows local connections
========================================================================
przemek@dev-01 ~ $ docker run \
>   -d \
>   --name zabbix \
>   -p 80:80 \
>   -p 10051:10051 \
>   --link zabbix-db:zabbix.db \
>   --env="DB_ADDRESS=zabbix.db" \
>   --env="DB_USER=zabbix" \
>   --env="DB_PASS=zabbix" \
>   zabbix/zabbix-server-2.4:2.4.5
eefffcd559b7c04910fca51abbfc8b3d63cd157eba1ad3d9bbb22cda19c2c6eb
przemek@dev-01 ~ $ docker exec -ti zabbix bash
[root@eefffcd559b7 /]# netstat -na
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:10050           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:10051           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:9111            0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.4:48036        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48044        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48030        172.17.0.3:3306         TIME_WAIT
tcp        0      0 172.17.0.4:48029        172.17.0.3:3306         TIME_WAIT
tcp        0      0 172.17.0.4:48046        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48037        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48035        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48028        172.17.0.3:3306         TIME_WAIT
tcp        0      0 172.17.0.4:48039        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48047        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48041        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48038        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48045        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48043        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48033        172.17.0.3:3306         TIME_WAIT
tcp        0      0 172.17.0.4:48042        172.17.0.3:3306         TIME_WAIT
tcp        0      0 172.17.0.4:48040        172.17.0.3:3306         ESTABLISHED
tcp        0      0 172.17.0.4:48032        172.17.0.3:3306         TIME_WAIT
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     37128    /var/run/php-fpm-www.sock
unix  3      [ ]         STREAM     CONNECTED     28646
unix  3      [ ]         STREAM     CONNECTED     28647
unix  3      [ ]         STREAM     CONNECTED     37127
unix  3      [ ]         STREAM     CONNECTED     28648
unix  3      [ ]         STREAM     CONNECTED     37126
unix  3      [ ]         STREAM     CONNECTED     28645
[root@eefffcd559b7 /]#
```

I Have used other way of connecting zabbix-server to database without exposing database port to any network interface and using option `--link container_name:address` Please try this way and let me know if it worked. 
I have spotted that in your zabbix-server `netstat -na` you haven't got active connection into database. Please look cosely to my logs. You can see a lot of connections into database on port `3306`.

Just edit run commands to looks something like this:

```
docker run \
  -d \
  --name zabbix-db \
  --env="MARIADB_USER=zabbix" \
  --env="MARIADB_PASS=zabbix" \
  million12/mariadb
```

```
docker run \
  -d \
  --name zabbix \
  -p 80:80 \
  -p 10051:10051 \
  --link zabbix-db:zabbix.db \
  --env="DB_ADDRESS=zabbix.db" \
  --env="DB_USER=zabbix" \
  --env="DB_PASS=zabbix" \
  zabbix/zabbix-server-2.4:2.4.5
```

**Comment by jangaraj** [comment]
Root cause:

```
--link zabbix-db:zabbix.db
```

is missing in README, zabbix-server conf uses only _zabbix.db_, user can specify  _--env="DB_ADDRESS=external DB IP"_, but result will be problem: 

```
2654:20150809:081349.725 [Z3001] connection to database 'zabbix' failed: [2005] Unknown MySQL server host 'zabbix.db' (0)
  2654:20150809:081349.725 database is down: reconnecting in 10 seconds
```

**Comment by aanc** [comment]
Hi,

@jangaraj indeed it seems to be the root cause. I managed to fix it by adding an entry to /etc/hosts for zabbix.db with the IP address defined in DB_ADDRESS when zabbix.db is not already defined (it will be defined only if the --link is specified)

I can submit a pull request if you think this solution is clean enough.

Another solution would be to update the config file.

**Comment by jangaraj** [comment]
PR is not needed, we will release new version soon.
@pozgo has fixed this issue https://github.com/million12/docker-zabbix-server
My more configurable version - https://github.com/jangaraj/zabbix-community-docker/tree/master/Dockerfile/zabbix-server-2.4 - I'm waiting only for review from @pozgo and then we will merge it to zabbix-community-docker repo.

**Comment by jangaraj** [comment]
Fixed

**Comment by barukasu** [comment]
I have the same issue in 2019.

I installed the **zabbix-appliance** docker container. The installation went fine but the agents can't connect to the server. It turns out port 10051 is not running in the container.

Here is how I installed the docker container

```
docker run --name asrc-zabbix -t \
      -p 10051:10051 \
      -p 16080:80 \
      -d zabbix/zabbix-appliance:latest
```

Port 80 is open the the webserver runs well

```
root@devtools:~# nmap -Pn localhost

Starting Nmap 7.60 ( https://nmap.org ) at 2019-07-17 22:52 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0000050s latency).
Other addresses for localhost (not scanned): ::1 10.51.96.10
Not shown: 996 closed ports
PORT      STATE SERVICE
22/tcp    open  ssh
80/tcp    open  http
111/tcp   open  rpcbind
16080/tcp open  osxwebadmin
```

also here is the status from the logs

```
   206:20190717:224400.263 Starting Zabbix Server. Zabbix 4.2.4 (revision 059af02).
   206:20190717:224400.263 ****** Enabled features ******
   206:20190717:224400.263 SNMP monitoring:           YES
   206:20190717:224400.263 IPMI monitoring:           YES
   206:20190717:224400.263 Web monitoring:            YES
   206:20190717:224400.263 VMware monitoring:         YES
   206:20190717:224400.264 SMTP authentication:       YES
   206:20190717:224400.264 Jabber notifications:       NO
   206:20190717:224400.264 Ez Texting notifications:  YES
   206:20190717:224400.264 ODBC:                      YES
   206:20190717:224400.264 SSH2 support:              YES
   206:20190717:224400.264 IPv6 support:              YES
   206:20190717:224400.265 TLS support:               YES
   206:20190717:224400.265 ******************************
   206:20190717:224400.265 using configuration file: /etc/zabbix/zabbix_server.conf
   206:20190717:224400.267 [Z3001] connection to database 'zabbix' failed: [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
   206:20190717:224400.267 database is down: reconnecting in 10 seconds
```

**Comment by jangaraj** [comment]
@barukasu you are using image made by Zabbix, so you need to ask @zabbix
